#!/bin/bash

# Script Name: system_report.sh
# Author: $(whoami)
# Date: $(date +"%Y-%m-%d %H:%M:%S")

# Variables to store system information
USERNAME=$(whoami)
CURRENT_DATE=$(date +"%Y-%m-%d %H:%M:%S")
HOSTNAME=$(hostname)
OS=$(source /etc/os-release && echo "$PRETTY_NAME")
UPTIME=$(uptime -p)

# Hardware Information
CPU=$(lshw -class processor | grep -m 1 'product' | awk -F': ' '{print $2}')
CPU_SPEED=$(lscpu | grep "CPU MHz" | awk '{print $3}')
RAM=$(free -h | grep Mem | awk '{print $2}')
DISKS=$(lsblk -o NAME,SIZE,MODEL | grep -v 'loop\|sr0')
VIDEO=$(lshw -class display | grep 'product' | awk -F': ' '{print $2}')

# Network Information
FQDN=$(hostname --fqdn)
IP_ADDRESS=$(hostname -I | awk '{print $1}')
GATEWAY=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd ", ")

# Interface Information
INTERFACE=$(ip link show | awk -F': ' '$1 ~ /^[0-9]+$/ {print $2}' | head -1)
CIDR_IP=$(ip -o -4 addr list $INTERFACE | awk '{print $4}')

# System Status
USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd ", ")
DISK_SPACE=$(df -h --output=avail / | tail -1 | tr -d '[:space:]')
PROCESS_COUNT=$(ps -e | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'load average:' '{print $2}' | sed 's/,//g')
MEMORY_ALLOCATION=$(free -h | grep Mem | awk '{print $3 "/" $2}')
LISTENING_PORTS=$(ss -tuln | awk 'NR>1 {print $5}' | awk -F':' '{print $NF}' | sort -n | uniq | paste -sd ", ")
UFW_RULES=$(sudo ufw status numbered 2>/dev/null || echo "UFW is inactive or requires sudo permissions.")

# Output the report
cat <<EOF

System Report generated by $USERNAME, $CURRENT_DATE

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
Speed: $CPU_SPEED MHz
RAM: $RAM
Disks:
$DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $IP_ADDRESS
Gateway IP: $GATEWAY
DNS Server(s): $DNS_SERVER

Interface Name: $INTERFACE
IP Address: $CIDR_IP

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISK_SPACE available
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: $MEMORY_ALLOCATION
Listening Network Ports: $LISTENING_PORTS
UFW Rules:
$UFW_RULES

EOF
